### ISSUE TITLE
seac-glyph outlining fails

### ISSUE THREAD

**Issue by LaurenzV** [RazrFalcon/ttf-parser#158] opened 2024-06-27 09:08 UTC
Given the following font: https://www.dafont.com/waltograph.font

Outlining the glyph aacute (glyph ID 157) fails, even though there clearly is an outline. This glyph uses the deprecated seac operator, so it's possible that we somehow have a bug when handling it.

**Comment by RazrFalcon** [comment] 2024-06-27 09:17
Will take a look.

>This glyph uses the deprecated seac operator

How do you know that?

**Comment by LaurenzV** [comment] 2024-06-27 09:23
I checked the charstring using fonttools.

**Comment by RazrFalcon** [comment] 2024-06-27 09:33
I see.

**Comment by RazrFalcon** [comment] 2024-06-27 09:49
>This glyph uses the deprecated seac operator, so it's possible that we somehow have a bug when handling it.

I got confused here. We do support `seac`. 
Parsing fails because of the MoveTo commands has 3 and not 2 values. We're getting `CFFError::InvalidArgumentsStackLength` in the end.

PS: I know that ttf-parser needs proper logging, I was trying to keep it dependency-free for the longest time.

**Comment by LaurenzV** [comment] 2024-06-27 09:52
I know we support it, by deprecated I mean it's deprecated by OpenType.

I think the issue you are encountering is only a symptom of the issue I fixed in the PR, though.

**Comment by RazrFalcon** [comment] 2024-06-27 09:58
Oh, I just saw the PR. Not sure it's the right way to do it. 
The issue is that we're handling the optional glyph width parameter incorrectly for some reason.

**Comment by LaurenzV** [comment] 2024-06-27 10:14
Hm, but I'm pretty sure that's the correct way to fix it... the whole reason that we have the context struct is that we can track whether we have an optional width argument as well as other things, right? And whenever we process a local or global subroutine we need to pass on that context because subroutines always need to be evaluated in the context they were invoked in, they can't be interpreted independently. However, in the case of seac, we are processing two independent glyphs with their own charstring program. They might or might not have an optional width parameter, independently of whether the original glyph has one.

**Comment by RazrFalcon** [comment] 2024-06-27 10:15
Closed by https://github.com/RazrFalcon/ttf-parser/commit/e7c9d2fac7c9b193d7782ba175e4f6aeef2def71

**Closed by RazrFalcon** 2024-06-27 10:15 UTC

**Comment by RazrFalcon** [comment] 2024-06-27 10:21
Yes, your solution is also correct, but I'm worried it has a higher chance of breaking something. It is better not to touch CFF parsing much, since we do not test it that well.
Right now, we create `CharStringParserContext` once per glyph. Who knows what side-effects we could get by having sub-contexts.

The problem is that `ttf-parser` assumes that glyph width in CFF is set only once. Which is a very strict requirement.
My solution simply ignores width if it was already set, which is a bit more forgiving and hopefully wouldn't break much.

**Comment by LaurenzV** [comment] 2024-06-27 12:02
It seems to fix the problem, so no objections from my side.

I don't have any bigger changes planned anymore, so if you want you can bump `ttf-parser` and `rustybuzz` now.

**Comment by RazrFalcon** [comment] 2024-06-27 13:47
Got it!
