### ISSUE TITLE
make c wrapper no_std

### ISSUE THREAD

**Issue by ebraminio** [RazrFalcon/ttf-parser#29] opened 2020-06-28 13:06 UTC
I am getting

`/usr/bin/ld: subprojects/ttf-parser/libttf_parser_capi.a(std-205127404fcba336.std.595pxchd-cgu.0.rcgu.o): undefined reference to symbol 'pthread_getattr_np@@GLIBC_2.2.5'`

and

`/usr/bin/ld: subprojects/ttf-parser/libttf_parser_capi.a(std-205127404fcba336.std.595pxchd-cgu.0.rcgu.o): in function 'std::sys::unix::weak::fetch':
/rustc/49cae55760da0a43428eba73abcb659bb70cf2e4//src/libstd/sys/unix/weak.rs:61: undefined reference to 'dlsym'`

if I don't pass `thread_dep, cpp.find_library('dl')` (which currently I am) and guess those are coming from rust's `std`, can c-api also become no_std so I can avoid passing https://github.com/harfbuzz/harfbuzz/pull/2510/files#diff-9356922ca3ded90602b144c3b5851dd2R8 pthread and libdl to it? Or is it something you are interested in at all so I can also have a look?

Thanks!

**Comment by RazrFalcon** [comment] 2020-06-28 13:48
>can c-api also become no_std 

Not sure if it's possible. Will take a look.

You should use dynamic linking. Static linking is kinda broken in Rust. At least for me. That's why `c-api` doesn't static at all. I guess it should be fixed in meson too.

**Comment by ebraminio** [comment] 2020-06-28 13:52
> Not sure if it's possible. Will take a look.

Thank you so much.

> You should use dynamic linking. Static linking is kinda broken in Rust. At least for me. That's why c-api doesn't build static at all. I guess it should be fixed in meson too.

Apparently I were able to somehow maybe at some limited cases, static linking is very convenient, am imagining some C library just embed a rust and itself can be embedded to another library easily.

**Comment by RazrFalcon** [comment] 2020-06-28 13:56
No, static linking via C API in rust is very troublesome. You should always use dynamic one.

**Comment by RazrFalcon** [comment] 2020-06-28 14:14
Yes, no_std no possible due to `std::panic::catch_unwind`. So meson should be changed to `cdylib`. 

Afaik, the problem with static linking is that rust links its own std with specific system libraries, which can cause conflicts during linking.

Personally, I always use dynamic linking for C API.

**Comment by ebraminio** [comment] 2020-06-28 14:51
Rust claims able to run on bare metal hardware but doesn't support static linking, that's very unfortunate :/ I wished it had some solution, maybe I getting it also as a dylib also and I'm unaware of it?

**Comment by RazrFalcon** [comment] 2020-06-28 14:55
It does support static linking. The problem is that you have to provide required libraries manually. pthread in your case. 

 `dylib` is a Rust dynamic library. You need `cdylib`, which is a C dynamic library.

**Comment by ebraminio** [comment] 2020-06-28 15:01
Oh I see, so its use is on [catch_unwind](https://github.com/RazrFalcon/ttf-parser/blob/a903730162f16cbc00c0c06408a8328480e1ae2f/c-api/lib.rs#L515-L516), `This method invokes a lot of parsing, so let's catch any panics just in case.`, is that to avoid panics from the beginning somehow? Is that anything worth to do? https://github.com/rust-lang/rfcs/issues/2810 is related I guess.

**Comment by RazrFalcon** [comment] 2020-06-28 15:04
>avoid panics from the beginning

It's one of the goals. But it will take a lot of time. Weeks.

**Comment by ebraminio** [comment] 2020-06-28 15:06
> It's one of the goals. But it will take a lot of time. Weeks.

Thank you so much, so there is a hope which is great! I will also try so to improve my Rust experience. Thanks

**Comment by notgull** [comment] 2023-03-08 17:14
> Yes, no_std no possible due to `std::panic::catch_unwind`. So meson should be changed to `cdylib`.

As an alternative to `catch_unwind`, you can use a drop-then-abort guard to prevent panics from unwinding into other code. This is `no_std`.

**Comment by RazrFalcon** [comment] 2023-03-13 06:51
@notgull can you elaborate?

**Comment by staticintlucas** [comment] 2023-03-22 18:25
I think what he means is something like:

```rust
struct DropAbortGuard;

impl DropAbortGuard {
    fn new() -> Self {
        Self
    }
    
    fn end(self) {
        core::mem::forget(self); // Ensures drop doesn't run for self
    }
}

impl Drop for DropAbortGuard {
    fn drop(&mut self) {
        panic!(); // Panic while panicing becomes an abort
    }
}

let guard = DropAbortGuard::new();

some_code_that_might_panic();

guard.end();
```

It's not pretty, but it seems to work.

**Comment by notgull** [comment] 2023-03-22 18:29
Yeah, you can find an example of this pattern [here](https://github.com/smol-rs/async-task/blob/9eb81969cce339462d993af135d0fc50f700d0d9/src/utils.rs#L25). Since you don't expect the code to panic anyways it should be a good fit

**Comment by RazrFalcon** [comment] 2023-03-22 18:41
Hmm... it simply replaces panic with abort, which is not what I want.
The whole point behind using `catch_unwind ` is that I cannot statically prove that ttf-parser will not panic. Sadly, this is the current Rust limitation. We need language-level `#[no-panic]` attribute first.

**Closed** 2023-03-22 18:42 UTC
